image: node:19.4.0

variables:
  IMAGE_NAME: gcr.io/diamond-pubreg/pato/frontend:$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA

stages:
  - test
  - build
  - sync

build-job:
  stage: test
  tags:
    - argus
  script:
    - yarn install
    - yarn build
  rules:
    - if: $CI_COMMIT_MESSAGE !~ /\[WIP\].*/

unit-test-job:
  stage: test
  tags: 
    - argus
  before_script:
    - yarn install
  script:
    # Tests cannot run concurrently, see https://github.com/mswjs/msw/issues/474
    - yarn run test --verbose --runInBand
  rules:
    - if: $CI_COMMIT_MESSAGE !~ /\[WIP\].*/
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

build-image:
  stage: build
  tags:
    - docker-image
  image:
    name: gcr.io/diamond-privreg/container-tools/kaniko-executor:v1.9.1-debug
    entrypoint: [""]
  only:
    - tags
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile --destination $IMAGE_NAME --build-arg API_ENDPOINT=/api/ --build-arg AUTH_ENDPOINT=/auth/ --build-arg VERSION=$CI_COMMIT_TAG

check-for-vulns:
  stage: build
  tags:
    - argus
  image:
    name: aquasec/trivy:0.42.1
    entrypoint: [""]
  only:
    - tags
  script:
    - trivy -s CRITICAL --exit-code 1 --ignore-unfixed $IMAGE_NAME
  needs:
    - build-image

sync-deploy-versions:
  stage: sync
  tags:
    - docker-image
  image:
    name: alpine/curl
  only:
    - tags
  script:
    - curl --request POST "https://${CI_SERVER_HOST}/api/v4/projects/6068/trigger/pipeline?token=${CI_PIPELINE_TRIGGER}&ref=${CI_DEFAULT_BRANCH}"

sync-github:
  stage: sync
  tags:
    - docker-image
  image:
    name: alpine/git
  only:
    - tags
  before_script:
    - apk add rsync
  script:
    - cd .. && git clone https://$CI_GITHUB_USER:$CI_GITHUB_TOKEN@github.com/diamondLightSource/pato-frontend.git github-upstream 
    - cd github-upstream
    - git remote update
    - git fetch 
    - rsync -r --exclude=.git --exclude=README.rst --exclude=.gitlab-ci.yml --exclude=nginx --exclude=.github --delete ../pato-frontend/ .
    - git config --local user.name "Guilherme de Freitas"
    - git config --local user.email guilherme.de-freitas@diamond.ac.uk
    - git add .
    - git commit -m "Release $CI_COMMIT_TAG"
    - git push origin $CI_DEFAULT_BRANCH

