approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - \@diamondlightsource/ui-components@*

yarnPath: .yarn/releases/yarn-4.18.0.cjs
